sudo: required

services:
  - docker
  
language: node_js

node_js:
  - "node"
  
before_install:
  - npm install -g gulp
  - npm install

install:
  - gulp 
  
script:
  - gulp build.debug
  - docker run -d --name paella-test-nginx -v `pwd`/build:/usr/share/nginx/html:ro nginx:alpine
  - docker run -d --name paella-test-selenium --link paella-test-nginx:paella -p 4444:4444 selenium/standalone-chrome:3.3.0
  - gulp test:local

after_script:
  - ls -l `pwd`/build

#before_deploy:
#  - sh ./.travis_scripts/prepate_deploy.sh 


